---

domain: staging.openfoodnetwork.org.uk
host_id: uk-staging
rails_env: staging

admin_email: dev.ofnuk@gmail.com

unicorn_timeout: 120

users_sysadmin:
  - "{{ core_devs }}"
  - lindhop
  - filipe
  - konrad
  - bethan
  - mohamed

# UK Staging is currently on holiday in Canada...
checkout_zone: Canada
country_code: CA
currency: CAD
locale: en_CA
available_locales: en_CA,fr_CA,cy
language: en.UTF-8
language_packages:
  - language-pack-en-base
l10n_repo: https://github.com/openfoodfoundation/l10n_ca.git
timezone: "Eastern Time (US & Canada)"

postgresql_version: 10

# Enable external database access for third party integrations
postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_n8n }}"
#  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }
