---

domain: openfoodnetwork.org.au
host_id: au-prod
rails_env: production

admin_email: maikel@openfoodnetwork.org.au

mail_domain: openfoodnetwork.org

# Optional list of subdomains to register in letsencrypt certificate
# Defaults to {{ domain }} if list is undefined
certbot_domains:
  - openfoodnetwork.org.au
  - www.openfoodnetwork.org.au
  - prod3.openfoodnetwork.org.au

# Size in bytes. You can also use units like 1G, 512MiB or 1000KB. See: `man fallocate`
# The default is `false`, not installing a swapfile.
swapfile_size: 4G

unicorn_timeout: 360

# Enable external database access for third party integrations
postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_n8n }}"
  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }
  - { type: hostssl, database: "{{ db }}", user: zapier, address: '167.99.89.242/32', auth_method: md5 } # for metabase (data.openfoodnetwork.org.au)

enable_rails_apm: "false" # has to be explicitly defined as a string due to some datadog bug

# Images settings
attachment_path: "public/images/spree/products/:id/:style/:basename.:extension"
attachment_url: ofn_production.s3.us-east-1.amazonaws.com
