---

domain: staging.openfoodnetwork.org.au
host_id: au-staging
rails_env: staging

admin_email: maikel@openfoodnetwork.org.au

mail_domain: "smtp.gmail.com"

users_sysadmin:
  - "{{ core_devs }}"
  - konrad

# activate the language switcher
available_locales: en,fr,es

# Depending on the resources of your server, you may want to adjust these.
unicorn_timeout: 120

# Size in bytes. You can also use units like 1G, 512MiB or 1000KB. See: `man fallocate`
# The default is `false`, not installing a swapfile.
swapfile_size: 1G

# Images settings
attachment_path: "public/images/spree/products/:id/:style/:basename.:extension"
attachment_url: ofn-staging.s3.us-east-1.amazonaws.com

postgresql_version: 13

# Enable external database access for third party integrations
postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_n8n }}"
  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }
