---

domain: openfoodnetwork.be
host_id: be-prod
rails_env: production

admin_email: admin@openfoodnetwork.be

mail_domain: openfoodnetwork.be

certbot_domains:
  - openfoodnetwork.be
  - www.openfoodnetwork.be

attachment_url: ofn-belgium.s3.us-east-1.amazonaws.com

# Enable external database access for third party integrations
postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_n8n }}"
#  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }
