---

domain: openfoodnetwork.ca
host_id: ca-prod
rails_env: production

admin_email: admin@openfoodnetwork.ca
mail_domain: openfoodnetwork.ca

unicorn_timeout: 360

certbot_domains:
  - openfoodnetwork.ca
  - www.openfoodnetwork.ca

postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_n8n }}"
  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }

enable_rails_apm: "false"
